name: Apartment Monitor

on:
  # schedule: #handled externally by cron-job.org github API job trigger
  #   # Run every 10 minutes
  #   - cron: '*/10 4-17 * * 1-5'
  workflow_dispatch: # keep manual trigger from GitHub UI


jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      SOZIALBAU_COOKIE: ${{ secrets.SOZIALBAU_COOKIE }}
      SOZIALBAU_JSESSIONID: ${{ secrets.SOZIALBAU_JSESSIONID }}
      SOZIALBAU_SERVERID: ${{ secrets.SOZIALBAU_SERVERID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-node-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: python src/main.py